version: "3"
services:
  back_app:
    depends_on:
      - mongodb-server
    restart: always
    build: .
    ports:
      - "9090:3000"
    volumes:
      - .:/usr/src/app
  mongodb-server:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb-server
volumes:
  mongo-data: